# Generated by Django 5.0.4 on 2024-04-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylaba', '0002_category_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
