# Generated by Django 4.1.3 on 2024-04-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_employeegroup_alter_women_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeGroup',
        ),
    ]
