# Generated by Django 4.1.3 on 2024-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sschet', models.CharField(max_length=50, verbose_name='Счёт')),
            ],
        ),
    ]
