# Generated by Django 5.0.4 on 2024-05-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_material_sschet'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_even',
            field=models.BooleanField(default=False),
        ),
    ]
