# Generated by Django 5.0.3 on 2024-05-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_material_is_even'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='is_even',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
