# Generated by Django 5.0.4 on 2024-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylaba', '0003_alter_category_options_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='photos/products/'),
        ),
    ]
