# Generated by Django 4.1.3 on 2024-04-24 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 4, 24))),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
