# Generated by Django 4.1.3 on 2024-04-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dalnoboy', '0004_alter_car_total_fuel_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='total_fuel_consumption',
        ),
    ]
