# Generated by Django 4.1.3 on 2024-04-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('fuel_consumption_per_km', models.FloatField()),
                ('total_fuel_consumption', models.FloatField(default=0)),
                ('mileage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_mileage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('fuel_spent', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dalnoboy.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dalnoboy.driver')),
            ],
        ),
    ]
