# Generated by Django 4.1.3 on 2024-04-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dalnoboy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='total_fuel_consumption',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption_per_km',
            field=models.FloatField(verbose_name='Расход топлива на 1км'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(default=0, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='total_mileage',
            field=models.FloatField(default=0, verbose_name='Пробег на всех авто.'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dalnoboy.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время выезда'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dalnoboy.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fuel_spent',
            field=models.FloatField(verbose_name='Затраченное топливо'),
        ),
    ]
