# Generated by Django 4.1.3 on 2024-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dalnoboy', '0002_remove_car_total_fuel_consumption_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_fuel_consumption',
            field=models.FloatField(default=0, verbose_name='Общий расход топлива.'),
            preserve_default=False,
        ),
    ]
