# Generated by Django 4.1.3 on 2024-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dalnoboy', '0003_car_total_fuel_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='total_fuel_consumption',
            field=models.FloatField(default=0, verbose_name='Общий расход топлива.'),
        ),
    ]
